// A simple data API that will be used to get the data for our
// components. On a real website, a more robust data fetching
// solution would be more appropriate.
const GapAPI = {
  gaps: [
    {
      slug: "total-full-time-wage-and-salary-workers",
      occupation_name: "Total, full-time wage and salary workers",
      parent_slug: null,
      year: "2019",
      number_workers: "117584",
      median_weekly_earnings: "917",
      men_number_workers: "65007",
      men_median_weekly_earnings: "1007",
      women_number_workers: "52577",
      women_median_weekly_earnings: "821",
      cents_to_dollar: "82"
    },
    {
      slug: "management-professional-and-related-occupations",
      occupation_name: "Management, professional, and related occupations",
      parent_slug: null,
      year: "2019",
      number_workers: "50119",
      median_weekly_earnings: "1309",
      men_number_workers: "24260",
      men_median_weekly_earnings: "1539",
      women_number_workers: "25859",
      women_median_weekly_earnings: "1135",
      cents_to_dollar: "74"
    },
    {
      slug: "management-business-and-financial-operations-occupations",
      occupation_name:
        "Management, business, and financial operations occupations",
      parent_slug: "management-professional-and-related-occupations",
      year: "2019",
      number_workers: "20696",
      median_weekly_earnings: "1415",
      men_number_workers: "11111",
      men_median_weekly_earnings: "1598",
      women_number_workers: "9585",
      women_median_weekly_earnings: "1221",
      cents_to_dollar: "76"
    },
    {
      slug: "management-occupations",
      occupation_name: "Management occupations",
      parent_slug: "management-business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "13948",
      median_weekly_earnings: "1478",
      men_number_workers: "8002",
      men_median_weekly_earnings: "1659",
      women_number_workers: "5946",
      women_median_weekly_earnings: "1266",
      cents_to_dollar: "76"
    },
    {
      slug: "chief-executives",
      occupation_name: "Chief executives",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "1113",
      median_weekly_earnings: "2380",
      men_number_workers: "812",
      men_median_weekly_earnings: "2509",
      women_number_workers: "302",
      women_median_weekly_earnings: "2019",
      cents_to_dollar: "80"
    },
    {
      slug: "general-and-operations-managers",
      occupation_name: "General and operations managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "990",
      median_weekly_earnings: "1384",
      men_number_workers: "678",
      men_median_weekly_earnings: "1476",
      women_number_workers: "312",
      women_median_weekly_earnings: "1153",
      cents_to_dollar: "78"
    },
    {
      slug: "marketing-and-sales-managers",
      occupation_name: "Marketing and sales managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "1109",
      median_weekly_earnings: "1600",
      men_number_workers: "591",
      men_median_weekly_earnings: "1895",
      women_number_workers: "518",
      women_median_weekly_earnings: "1393",
      cents_to_dollar: "74"
    },
    {
      slug: "administrative-services-managers",
      occupation_name: "Administrative services managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "154",
      median_weekly_earnings: "1235",
      men_number_workers: "93",
      men_median_weekly_earnings: "1277",
      women_number_workers: "61",
      women_median_weekly_earnings: "1084",
      cents_to_dollar: "85"
    },
    {
      slug: "computer-and-information-systems-managers",
      occupation_name: "Computer and information systems managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "629",
      median_weekly_earnings: "1984",
      men_number_workers: "439",
      men_median_weekly_earnings: "2019",
      women_number_workers: "190",
      women_median_weekly_earnings: "1892",
      cents_to_dollar: "94"
    },
    {
      slug: "financial-managers",
      occupation_name: "Financial managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "1142",
      median_weekly_earnings: "1447",
      men_number_workers: "523",
      men_median_weekly_earnings: "1897",
      women_number_workers: "619",
      women_median_weekly_earnings: "1207",
      cents_to_dollar: "64"
    },
    {
      slug: "human-resources-managers",
      occupation_name: "Human resources managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "299",
      median_weekly_earnings: "1592",
      men_number_workers: "69",
      men_median_weekly_earnings: "1829",
      women_number_workers: "230",
      women_median_weekly_earnings: "1538",
      cents_to_dollar: "84"
    },
    {
      slug: "purchasing-managers",
      occupation_name: "Purchasing managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "214",
      median_weekly_earnings: "1539",
      men_number_workers: "129",
      men_median_weekly_earnings: "1657",
      women_number_workers: "84",
      women_median_weekly_earnings: "1390",
      cents_to_dollar: "84"
    },
    {
      slug: "construction-managers",
      occupation_name: "Construction managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "610",
      median_weekly_earnings: "1468",
      men_number_workers: "539",
      men_median_weekly_earnings: "1511",
      women_number_workers: "71",
      women_median_weekly_earnings: "1210",
      cents_to_dollar: "80"
    },
    {
      slug: "education-administrators",
      occupation_name: "Education administrators",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "811",
      median_weekly_earnings: "1371",
      men_number_workers: "276",
      men_median_weekly_earnings: "1467",
      women_number_workers: "536",
      women_median_weekly_earnings: "1335",
      cents_to_dollar: "91"
    },
    {
      slug: "food-service-managers",
      occupation_name: "Food service managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "785",
      median_weekly_earnings: "863",
      men_number_workers: "420",
      men_median_weekly_earnings: "964",
      women_number_workers: "365",
      women_median_weekly_earnings: "719",
      cents_to_dollar: "75"
    },
    {
      slug: "lodging-managers",
      occupation_name: "Lodging managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "116",
      median_weekly_earnings: "975",
      men_number_workers: "61",
      men_median_weekly_earnings: "1096",
      women_number_workers: "55",
      women_median_weekly_earnings: "894",
      cents_to_dollar: "82"
    },
    {
      slug: "medical-and-health-services-managers",
      occupation_name: "Medical and health services managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "578",
      median_weekly_earnings: "1478",
      men_number_workers: "169",
      men_median_weekly_earnings: "1828",
      women_number_workers: "409",
      women_median_weekly_earnings: "1362",
      cents_to_dollar: "75"
    },
    {
      slug: "property-real-estate-and-community-association-managers",
      occupation_name:
        "Property, real estate, and community association managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "438",
      median_weekly_earnings: "954",
      men_number_workers: "214",
      men_median_weekly_earnings: "1168",
      women_number_workers: "224",
      women_median_weekly_earnings: "849",
      cents_to_dollar: "73"
    },
    {
      slug: "social-and-community-service-managers",
      occupation_name: "Social and community service managers",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "403",
      median_weekly_earnings: "1243",
      men_number_workers: "143",
      men_median_weekly_earnings: "1452",
      women_number_workers: "260",
      women_median_weekly_earnings: "1156",
      cents_to_dollar: "80"
    },
    {
      slug: "managers-all-other",
      occupation_name: "Managers, all other",
      parent_slug: "management-occupations",
      year: "2019",
      number_workers: "3497",
      median_weekly_earnings: "1533",
      men_number_workers: "2088",
      men_median_weekly_earnings: "1725",
      women_number_workers: "1409",
      women_median_weekly_earnings: "1317",
      cents_to_dollar: "76"
    },
    {
      slug: "business-and-financial-operations-occupations",
      occupation_name: "Business and financial operations occupations",
      parent_slug: "management-business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "6748",
      median_weekly_earnings: "1285",
      men_number_workers: "3109",
      men_median_weekly_earnings: "1468",
      women_number_workers: "3639",
      women_median_weekly_earnings: "1148",
      cents_to_dollar: "78"
    },
    {
      slug: "wholesale-and-retail-buyers-except-farm-products",
      occupation_name: "Wholesale and retail buyers, except farm products",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "162",
      median_weekly_earnings: "979",
      men_number_workers: "87",
      men_median_weekly_earnings: "982",
      women_number_workers: "76",
      women_median_weekly_earnings: "977",
      cents_to_dollar: "99"
    },
    {
      slug: "purchasing-agents-except-wholesale-retail-and-farm-products",
      occupation_name:
        "Purchasing agents, except wholesale, retail, and farm products",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "248",
      median_weekly_earnings: "1170",
      men_number_workers: "134",
      men_median_weekly_earnings: "1202",
      women_number_workers: "113",
      women_median_weekly_earnings: "1081",
      cents_to_dollar: "90"
    },
    {
      slug: "claims-adjusters-appraisers-examiners-and-investigators",
      occupation_name:
        "Claims adjusters, appraisers, examiners, and investigators",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "299",
      median_weekly_earnings: "1103",
      men_number_workers: "104",
      men_median_weekly_earnings: "1277",
      women_number_workers: "195",
      women_median_weekly_earnings: "972",
      cents_to_dollar: "76"
    },
    {
      slug: "compliance-officers",
      occupation_name: "Compliance officers",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "271",
      median_weekly_earnings: "1346",
      men_number_workers: "105",
      men_median_weekly_earnings: "1561",
      women_number_workers: "165",
      women_median_weekly_earnings: "1264",
      cents_to_dollar: "81"
    },
    {
      slug: "human-resources-workers",
      occupation_name: "Human resources workers",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "680",
      median_weekly_earnings: "1203",
      men_number_workers: "186",
      men_median_weekly_earnings: "1325",
      women_number_workers: "494",
      women_median_weekly_earnings: "1149",
      cents_to_dollar: "87"
    },
    {
      slug: "training-and-development-specialists",
      occupation_name: "Training and development specialists",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "120",
      median_weekly_earnings: "1127",
      men_number_workers: "51",
      men_median_weekly_earnings: "1249",
      women_number_workers: "68",
      women_median_weekly_earnings: "968",
      cents_to_dollar: "78"
    },
    {
      slug: "management-analysts",
      occupation_name: "Management analysts",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "692",
      median_weekly_earnings: "1622",
      men_number_workers: "389",
      men_median_weekly_earnings: "1870",
      women_number_workers: "303",
      women_median_weekly_earnings: "1517",
      cents_to_dollar: "81"
    },
    {
      slug: "market-research-analysts-and-marketing-specialists",
      occupation_name: "Market research analysts and marketing specialists",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "281",
      median_weekly_earnings: "1363",
      men_number_workers: "130",
      men_median_weekly_earnings: "1688",
      women_number_workers: "152",
      women_median_weekly_earnings: "1228",
      cents_to_dollar: "73"
    },
    {
      slug: "business-operations-specialists-all-other",
      occupation_name: "Business operations specialists, all other",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "248",
      median_weekly_earnings: "1283",
      men_number_workers: "100",
      men_median_weekly_earnings: "1540",
      women_number_workers: "148",
      women_median_weekly_earnings: "1193",
      cents_to_dollar: "77"
    },
    {
      slug: "accountants-and-auditors",
      occupation_name: "Accountants and auditors",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "1683",
      median_weekly_earnings: "1221",
      men_number_workers: "670",
      men_median_weekly_earnings: "1419",
      women_number_workers: "1013",
      women_median_weekly_earnings: "1141",
      cents_to_dollar: "80"
    },
    {
      slug: "financial-analysts",
      occupation_name: "Financial analysts",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "307",
      median_weekly_earnings: "1613",
      men_number_workers: "203",
      men_median_weekly_earnings: "1763",
      women_number_workers: "104",
      women_median_weekly_earnings: "1386",
      cents_to_dollar: "79"
    },
    {
      slug: "personal-financial-advisors",
      occupation_name: "Personal financial advisors",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "448",
      median_weekly_earnings: "1618",
      men_number_workers: "296",
      men_median_weekly_earnings: "1905",
      women_number_workers: "152",
      women_median_weekly_earnings: "1232",
      cents_to_dollar: "65"
    },
    {
      slug: "insurance-underwriters",
      occupation_name: "Insurance underwriters",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "116",
      median_weekly_earnings: "1169",
      men_number_workers: "57",
      men_median_weekly_earnings: "1338",
      women_number_workers: "59",
      women_median_weekly_earnings: "1142",
      cents_to_dollar: "85"
    },
    {
      slug: "credit-counselors-and-loan-officers",
      occupation_name: "Credit counselors and loan officers",
      parent_slug: "business-and-financial-operations-occupations",
      year: "2019",
      number_workers: "366",
      median_weekly_earnings: "1235",
      men_number_workers: "173",
      men_median_weekly_earnings: "1542",
      women_number_workers: "193",
      women_median_weekly_earnings: "1020",
      cents_to_dollar: "66"
    },
    {
      slug: "professional-and-related-occupations",
      occupation_name: "Professional and related occupations",
      parent_slug: "management-professional-and-related-occupations",
      year: "2019",
      number_workers: "29423",
      median_weekly_earnings: "1237",
      men_number_workers: "13149",
      men_median_weekly_earnings: "1493",
      women_number_workers: "16274",
      women_median_weekly_earnings: "1085",
      cents_to_dollar: "73"
    },
    {
      slug: "computer-and-mathematical-occupations",
      occupation_name: "Computer and mathematical occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "4947",
      median_weekly_earnings: "1579",
      men_number_workers: "3668",
      men_median_weekly_earnings: "1658",
      women_number_workers: "1279",
      women_median_weekly_earnings: "1353",
      cents_to_dollar: "82"
    },
    {
      slug: "computer-systems-analysts",
      occupation_name: "Computer systems analysts",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "623",
      median_weekly_earnings: "1461",
      men_number_workers: "368",
      men_median_weekly_earnings: "1580",
      women_number_workers: "255",
      women_median_weekly_earnings: "1289",
      cents_to_dollar: "82"
    },
    {
      slug: "computer-programmers",
      occupation_name: "Computer programmers",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "425",
      median_weekly_earnings: "1586",
      men_number_workers: "343",
      men_median_weekly_earnings: "1613",
      women_number_workers: "82",
      women_median_weekly_earnings: "1463",
      cents_to_dollar: "91"
    },
    {
      slug: "software-developers-applications-and-systems-software",
      occupation_name: "Software developers, applications and systems software",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "1714",
      median_weekly_earnings: "1894",
      men_number_workers: "1379",
      men_median_weekly_earnings: "1920",
      women_number_workers: "335",
      women_median_weekly_earnings: "1718",
      cents_to_dollar: "89"
    },
    {
      slug: "web-developers",
      occupation_name: "Web developers",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "144",
      median_weekly_earnings: "1470",
      men_number_workers: "88",
      men_median_weekly_earnings: "1633",
      women_number_workers: "56",
      women_median_weekly_earnings: "1150",
      cents_to_dollar: "70"
    },
    {
      slug: "computer-support-specialists",
      occupation_name: "Computer support specialists",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "486",
      median_weekly_earnings: "1192",
      men_number_workers: "365",
      men_median_weekly_earnings: "1223",
      women_number_workers: "121",
      women_median_weekly_earnings: "1103",
      cents_to_dollar: "90"
    },
    {
      slug: "network-and-computer-systems-administrators",
      occupation_name: "Network and computer systems administrators",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "194",
      median_weekly_earnings: "1447",
      men_number_workers: "144",
      men_median_weekly_earnings: "1541",
      women_number_workers: "50",
      women_median_weekly_earnings: "1233",
      cents_to_dollar: "80"
    },
    {
      slug: "computer-occupations-all-other",
      occupation_name: "Computer occupations, all other",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "721",
      median_weekly_earnings: "1277",
      men_number_workers: "542",
      men_median_weekly_earnings: "1365",
      women_number_workers: "179",
      women_median_weekly_earnings: "1148",
      cents_to_dollar: "84"
    },
    {
      slug: "operations-research-analysts",
      occupation_name: "Operations research analysts",
      parent_slug: "computer-and-mathematical-occupations",
      year: "2019",
      number_workers: "153",
      median_weekly_earnings: "1512",
      men_number_workers: "86",
      men_median_weekly_earnings: "1753",
      women_number_workers: "67",
      women_median_weekly_earnings: "1188",
      cents_to_dollar: "68"
    },
    {
      slug: "architecture-and-engineering-occupations",
      occupation_name: "Architecture and engineering occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "3011",
      median_weekly_earnings: "1550",
      men_number_workers: "2559",
      men_median_weekly_earnings: "1589",
      women_number_workers: "452",
      women_median_weekly_earnings: "1339",
      cents_to_dollar: "84"
    },
    {
      slug: "civil-engineers",
      occupation_name: "Civil engineers",
      parent_slug: "architecture-and-engineering-occupations",
      year: "2019",
      number_workers: "421",
      median_weekly_earnings: "1616",
      men_number_workers: "360",
      men_median_weekly_earnings: "1657",
      women_number_workers: "61",
      women_median_weekly_earnings: "1353",
      cents_to_dollar: "82"
    },
    {
      slug: "industrial-engineers-including-health-and-safety",
      occupation_name: "Industrial engineers, including health and safety",
      parent_slug: "architecture-and-engineering-occupations",
      year: "2019",
      number_workers: "227",
      median_weekly_earnings: "1589",
      men_number_workers: "169",
      men_median_weekly_earnings: "1616",
      women_number_workers: "58",
      women_median_weekly_earnings: "1487",
      cents_to_dollar: "92"
    },
    {
      slug: "engineers-all-other",
      occupation_name: "Engineers, all other",
      parent_slug: "architecture-and-engineering-occupations",
      year: "2019",
      number_workers: "529",
      median_weekly_earnings: "1636",
      men_number_workers: "455",
      men_median_weekly_earnings: "1663",
      women_number_workers: "74",
      women_median_weekly_earnings: "1446",
      cents_to_dollar: "87"
    },
    {
      slug: "engineering-technicians-except-drafters",
      occupation_name: "Engineering technicians, except drafters",
      parent_slug: "architecture-and-engineering-occupations",
      year: "2019",
      number_workers: "462",
      median_weekly_earnings: "1161",
      men_number_workers: "382",
      men_median_weekly_earnings: "1200",
      women_number_workers: "79",
      women_median_weekly_earnings: "915",
      cents_to_dollar: "76"
    },
    {
      slug: "life-physical-and-social-science-occupations",
      occupation_name: "Life, physical, and social science occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "1233",
      median_weekly_earnings: "1334",
      men_number_workers: "676",
      men_median_weekly_earnings: "1447",
      women_number_workers: "556",
      women_median_weekly_earnings: "1237",
      cents_to_dollar: "85"
    },
    {
      slug: "medical-scientists",
      occupation_name: "Medical scientists",
      parent_slug: "life-physical-and-social-science-occupations",
      year: "2019",
      number_workers: "146",
      median_weekly_earnings: "1188",
      men_number_workers: "77",
      men_median_weekly_earnings: "1214",
      women_number_workers: "70",
      women_median_weekly_earnings: "1175",
      cents_to_dollar: "97"
    },
    {
      slug: "physical-scientists-all-other",
      occupation_name: "Physical scientists, all other",
      parent_slug: "life-physical-and-social-science-occupations",
      year: "2019",
      number_workers: "278",
      median_weekly_earnings: "1669",
      men_number_workers: "158",
      men_median_weekly_earnings: "1901",
      women_number_workers: "120",
      women_median_weekly_earnings: "1385",
      cents_to_dollar: "73"
    },
    {
      slug: "miscellaneous-life-physical-and-social-science-technicians",
      occupation_name:
        "Miscellaneous life, physical, and social science technicians",
      parent_slug: "life-physical-and-social-science-occupations",
      year: "2019",
      number_workers: "108",
      median_weekly_earnings: "907",
      men_number_workers: "57",
      men_median_weekly_earnings: "928",
      women_number_workers: "51",
      women_median_weekly_earnings: "896",
      cents_to_dollar: "97"
    },
    {
      slug: "community-and-social-service-occupations",
      occupation_name: "Community and social service occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "2240",
      median_weekly_earnings: "968",
      men_number_workers: "742",
      men_median_weekly_earnings: "1064",
      women_number_workers: "1498",
      women_median_weekly_earnings: "941",
      cents_to_dollar: "88"
    },
    {
      slug: "social-workers",
      occupation_name: "Social workers",
      parent_slug: "community-and-social-service-occupations",
      year: "2019",
      number_workers: "739",
      median_weekly_earnings: "964",
      men_number_workers: "136",
      men_median_weekly_earnings: "1108",
      women_number_workers: "603",
      women_median_weekly_earnings: "944",
      cents_to_dollar: "85"
    },
    {
      slug: "clergy",
      occupation_name: "Clergy",
      parent_slug: "community-and-social-service-occupations",
      year: "2019",
      number_workers: "332",
      median_weekly_earnings: "1066",
      men_number_workers: "275",
      men_median_weekly_earnings: "1155",
      women_number_workers: "57",
      women_median_weekly_earnings: "862",
      cents_to_dollar: "75"
    },
    {
      slug: "legal-occupations",
      occupation_name: "Legal occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "1478",
      median_weekly_earnings: "1562",
      men_number_workers: "670",
      men_median_weekly_earnings: "1999",
      women_number_workers: "808",
      women_median_weekly_earnings: "1266",
      cents_to_dollar: "63"
    },
    {
      slug: "lawyers",
      occupation_name: "Lawyers",
      parent_slug: "legal-occupations",
      year: "2019",
      number_workers: "884",
      median_weekly_earnings: "2043",
      men_number_workers: "548",
      men_median_weekly_earnings: "2202",
      women_number_workers: "336",
      women_median_weekly_earnings: "1878",
      cents_to_dollar: "85"
    },
    {
      slug: "education-training-and-library-occupations",
      occupation_name: "Education, training, and library occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "7238",
      median_weekly_earnings: "1057",
      men_number_workers: "1991",
      men_median_weekly_earnings: "1265",
      women_number_workers: "5247",
      women_median_weekly_earnings: "987",
      cents_to_dollar: "78"
    },
    {
      slug: "postsecondary-teachers",
      occupation_name: "Postsecondary teachers",
      parent_slug: "education-training-and-library-occupations",
      year: "2019",
      number_workers: "986",
      median_weekly_earnings: "1512",
      men_number_workers: "544",
      men_median_weekly_earnings: "1670",
      women_number_workers: "442",
      women_median_weekly_earnings: "1358",
      cents_to_dollar: "81"
    },
    {
      slug: "elementary-and-middle-school-teachers",
      occupation_name: "Elementary and middle school teachers",
      parent_slug: "education-training-and-library-occupations",
      year: "2019",
      number_workers: "3162",
      median_weekly_earnings: "1067",
      men_number_workers: "640",
      men_median_weekly_earnings: "1161",
      women_number_workers: "2522",
      women_median_weekly_earnings: "1042",
      cents_to_dollar: "90"
    },
    {
      slug: "secondary-school-teachers",
      occupation_name: "Secondary school teachers",
      parent_slug: "education-training-and-library-occupations",
      year: "2019",
      number_workers: "882",
      median_weekly_earnings: "1161",
      men_number_workers: "408",
      men_median_weekly_earnings: "1262",
      women_number_workers: "474",
      women_median_weekly_earnings: "1095",
      cents_to_dollar: "87"
    },
    {
      slug: "other-teachers-and-instructors",
      occupation_name: "Other teachers and instructors",
      parent_slug: "education-training-and-library-occupations",
      year: "2019",
      number_workers: "455",
      median_weekly_earnings: "1054",
      men_number_workers: "192",
      men_median_weekly_earnings: "1190",
      women_number_workers: "263",
      women_median_weekly_earnings: "942",
      cents_to_dollar: "79"
    },
    {
      slug: "teacher-assistants",
      occupation_name: "Teacher assistants",
      parent_slug: "education-training-and-library-occupations",
      year: "2019",
      number_workers: "637",
      median_weekly_earnings: "590",
      men_number_workers: "72",
      men_median_weekly_earnings: "707",
      women_number_workers: "565",
      women_median_weekly_earnings: "579",
      cents_to_dollar: "82"
    },
    {
      slug: "arts-design-entertainment-sports-and-media-occupations",
      occupation_name:
        "Arts, design, entertainment, sports, and media occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "1762",
      median_weekly_earnings: "1151",
      men_number_workers: "956",
      men_median_weekly_earnings: "1231",
      women_number_workers: "806",
      women_median_weekly_earnings: "1077",
      cents_to_dollar: "87"
    },
    {
      slug: "designers",
      occupation_name: "Designers",
      parent_slug: "arts-design-entertainment-sports-and-media-occupations",
      year: "2019",
      number_workers: "661",
      median_weekly_earnings: "1126",
      men_number_workers: "337",
      men_median_weekly_earnings: "1214",
      women_number_workers: "324",
      women_median_weekly_earnings: "1052",
      cents_to_dollar: "87"
    },
    {
      slug: "producers-and-directors",
      occupation_name: "Producers and directors",
      parent_slug: "arts-design-entertainment-sports-and-media-occupations",
      year: "2019",
      number_workers: "109",
      median_weekly_earnings: "1483",
      men_number_workers: "59",
      men_median_weekly_earnings: "1652",
      women_number_workers: "50",
      women_median_weekly_earnings: "1156",
      cents_to_dollar: "70"
    },
    {
      slug: "healthcare-practitioners-and-technical-occupations",
      occupation_name: "Healthcare practitioners and technical occupations",
      parent_slug: "professional-and-related-occupations",
      year: "2019",
      number_workers: "7514",
      median_weekly_earnings: "1180",
      men_number_workers: "1887",
      men_median_weekly_earnings: "1422",
      women_number_workers: "5627",
      women_median_weekly_earnings: "1130",
      cents_to_dollar: "79"
    },
    {
      slug: "pharmacists",
      occupation_name: "Pharmacists",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "255",
      median_weekly_earnings: "2013",
      men_number_workers: "100",
      men_median_weekly_earnings: "2245",
      women_number_workers: "155",
      women_median_weekly_earnings: "1877",
      cents_to_dollar: "84"
    },
    {
      slug: "physicians-and-surgeons",
      occupation_name: "Physicians and surgeons",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "857",
      median_weekly_earnings: "2292",
      men_number_workers: "507",
      men_median_weekly_earnings: "2500",
      women_number_workers: "349",
      women_median_weekly_earnings: "1878",
      cents_to_dollar: "75"
    },
    {
      slug: "physical-therapists",
      occupation_name: "Physical therapists",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "211",
      median_weekly_earnings: "1431",
      men_number_workers: "81",
      men_median_weekly_earnings: "1610",
      women_number_workers: "130",
      women_median_weekly_earnings: "1323",
      cents_to_dollar: "82"
    },
    {
      slug: "registered-nurses",
      occupation_name: "Registered nurses",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "2640",
      median_weekly_earnings: "1223",
      men_number_workers: "320",
      men_median_weekly_earnings: "1256",
      women_number_workers: "2321",
      women_median_weekly_earnings: "1217",
      cents_to_dollar: "97"
    },
    {
      slug: "clinical-laboratory-technologists-and-technicians",
      occupation_name: "Clinical laboratory technologists and technicians",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "281",
      median_weekly_earnings: "979",
      men_number_workers: "66",
      men_median_weekly_earnings: "1117",
      women_number_workers: "215",
      women_median_weekly_earnings: "952",
      cents_to_dollar: "85"
    },
    {
      slug: "diagnostic-related-technologists-and-technicians",
      occupation_name: "Diagnostic related technologists and technicians",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "320",
      median_weekly_earnings: "1126",
      men_number_workers: "107",
      men_median_weekly_earnings: "1166",
      women_number_workers: "213",
      women_median_weekly_earnings: "1076",
      cents_to_dollar: "92"
    },
    {
      slug: "emergency-medical-technicians-and-paramedics",
      occupation_name: "Emergency medical technicians and paramedics",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "179",
      median_weekly_earnings: "912",
      men_number_workers: "125",
      men_median_weekly_earnings: "991",
      women_number_workers: "54",
      women_median_weekly_earnings: "786",
      cents_to_dollar: "79"
    },
    {
      slug: "health-practitioner-support-technologists-and-technicians",
      occupation_name:
        "Health practitioner support technologists and technicians",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "570",
      median_weekly_earnings: "735",
      men_number_workers: "126",
      men_median_weekly_earnings: "843",
      women_number_workers: "444",
      women_median_weekly_earnings: "712",
      cents_to_dollar: "84"
    },
    {
      slug: "licensed-practical-and-licensed-vocational-nurses",
      occupation_name: "Licensed practical and licensed vocational nurses",
      parent_slug: "healthcare-practitioners-and-technical-occupations",
      year: "2019",
      number_workers: "533",
      median_weekly_earnings: "806",
      men_number_workers: "53",
      men_median_weekly_earnings: "896",
      women_number_workers: "481",
      women_median_weekly_earnings: "799",
      cents_to_dollar: "89"
    },
    {
      slug: "service-occupations",
      occupation_name: "Service occupations",
      parent_slug: null,
      year: "2019",
      number_workers: "16558",
      median_weekly_earnings: "592",
      men_number_workers: "7898",
      men_median_weekly_earnings: "659",
      women_number_workers: "8660",
      women_median_weekly_earnings: "537",
      cents_to_dollar: "81"
    },
    {
      slug: "healthcare-support-occupations",
      occupation_name: "Healthcare support occupations",
      parent_slug: "service-occupations",
      year: "2019",
      number_workers: "2700",
      median_weekly_earnings: "591",
      men_number_workers: "363",
      men_median_weekly_earnings: "639",
      women_number_workers: "2337",
      women_median_weekly_earnings: "585",
      cents_to_dollar: "92"
    },
    {
      slug: "nursing-psychiatric-and-home-health-aides",
      occupation_name: "Nursing, psychiatric, and home health aides",
      parent_slug: "healthcare-support-occupations",
      year: "2019",
      number_workers: "1471",
      median_weekly_earnings: "562",
      men_number_workers: "184",
      men_median_weekly_earnings: "588",
      women_number_workers: "1287",
      women_median_weekly_earnings: "556",
      cents_to_dollar: "95"
    },
    {
      slug: "protective-service-occupations",
      occupation_name: "Protective service occupations",
      parent_slug: "service-occupations",
      year: "2019",
      number_workers: "2725",
      median_weekly_earnings: "900",
      men_number_workers: "2172",
      men_median_weekly_earnings: "953",
      women_number_workers: "553",
      women_median_weekly_earnings: "731",
      cents_to_dollar: "77"
    },
    {
      slug: "bailiffs-correctional-officers-and-jailers",
      occupation_name: "Bailiffs, correctional officers, and jailers",
      parent_slug: "protective-service-occupations",
      year: "2019",
      number_workers: "365",
      median_weekly_earnings: "776",
      men_number_workers: "251",
      men_median_weekly_earnings: "890",
      women_number_workers: "114",
      women_median_weekly_earnings: "664",
      cents_to_dollar: "75"
    },
    {
      slug: "police-and-sheriffs-patrol-officers",
      occupation_name: "Police and sheriff's patrol officers",
      parent_slug: "protective-service-occupations",
      year: "2019",
      number_workers: "686",
      median_weekly_earnings: "1111",
      men_number_workers: "559",
      men_median_weekly_earnings: "1143",
      women_number_workers: "127",
      women_median_weekly_earnings: "922",
      cents_to_dollar: "81"
    },
    {
      slug: "security-guards-and-gaming-surveillance-officers",
      occupation_name: "Security guards and gaming surveillance officers",
      parent_slug: "protective-service-occupations",
      year: "2019",
      number_workers: "790",
      median_weekly_earnings: "650",
      men_number_workers: "631",
      men_median_weekly_earnings: "671",
      women_number_workers: "159",
      women_median_weekly_earnings: "589",
      cents_to_dollar: "88"
    },
    {
      slug: "food-preparation-and-serving-related-occupations",
      occupation_name: "Food preparation and serving related occupations",
      parent_slug: "service-occupations",
      year: "2019",
      number_workers: "4689",
      median_weekly_earnings: "522",
      men_number_workers: "2352",
      men_median_weekly_earnings: "576",
      women_number_workers: "2337",
      women_median_weekly_earnings: "492",
      cents_to_dollar: "85"
    },
    {
      slug: "chefs-and-head-cooks",
      occupation_name: "Chefs and head cooks",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "406",
      median_weekly_earnings: "698",
      men_number_workers: "334",
      men_median_weekly_earnings: "727",
      women_number_workers: "72",
      women_median_weekly_earnings: "553",
      cents_to_dollar: "76"
    },
    {
      slug: "first-line-supervisors-of-food-preparation-and-serving-workers",
      occupation_name:
        "First-line supervisors of food preparation and serving workers",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "426",
      median_weekly_earnings: "584",
      men_number_workers: "184",
      men_median_weekly_earnings: "657",
      women_number_workers: "242",
      women_median_weekly_earnings: "545",
      cents_to_dollar: "83"
    },
    {
      slug: "cooks",
      occupation_name: "Cooks",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "1362",
      median_weekly_earnings: "512",
      men_number_workers: "831",
      men_median_weekly_earnings: "535",
      women_number_workers: "531",
      women_median_weekly_earnings: "489",
      cents_to_dollar: "91"
    },
    {
      slug: "food-preparation-workers",
      occupation_name: "Food preparation workers",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "574",
      median_weekly_earnings: "496",
      men_number_workers: "246",
      men_median_weekly_earnings: "532",
      women_number_workers: "328",
      women_median_weekly_earnings: "463",
      cents_to_dollar: "87"
    },
    {
      slug: "bartenders",
      occupation_name: "Bartenders",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "293",
      median_weekly_earnings: "610",
      men_number_workers: "159",
      men_median_weekly_earnings: "655",
      women_number_workers: "134",
      women_median_weekly_earnings: "578",
      cents_to_dollar: "88"
    },
    {
      slug: "waiters-and-waitresses",
      occupation_name: "Waiters and waitresses",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "973",
      median_weekly_earnings: "511",
      men_number_workers: "292",
      men_median_weekly_earnings: "594",
      women_number_workers: "681",
      women_median_weekly_earnings: "491",
      cents_to_dollar: "83"
    },
    {
      slug: "dining-room-and-cafeteria-attendants-and-bartender-helpers",
      occupation_name:
        "Dining room and cafeteria attendants and bartender helpers",
      parent_slug: "food-preparation-and-serving-related-occupations",
      year: "2019",
      number_workers: "116",
      median_weekly_earnings: "554",
      men_number_workers: "66",
      men_median_weekly_earnings: "605",
      women_number_workers: "50",
      women_median_weekly_earnings: "513",
      cents_to_dollar: "85"
    },
    {
      slug: "building-and-grounds-cleaning-and-maintenance-occupations",
      occupation_name:
        "Building and grounds cleaning and maintenance occupations",
      parent_slug: "service-occupations",
      year: "2019",
      number_workers: "3679",
      median_weekly_earnings: "580",
      men_number_workers: "2293",
      men_median_weekly_earnings: "618",
      women_number_workers: "1386",
      women_median_weekly_earnings: "502",
      cents_to_dollar: "81"
    },
    {
      slug: "first-line-supervisors-of-housekeeping-and-janitorial-workers",
      occupation_name:
        "First-line supervisors of housekeeping and janitorial workers",
      parent_slug: "building-and-grounds-cleaning-and-maintenance-occupations",
      year: "2019",
      number_workers: "215",
      median_weekly_earnings: "710",
      men_number_workers: "134",
      men_median_weekly_earnings: "758",
      women_number_workers: "80",
      women_median_weekly_earnings: "639",
      cents_to_dollar: "84"
    },
    {
      slug: "janitors-and-building-cleaners",
      occupation_name: "Janitors and building cleaners",
      parent_slug: "building-and-grounds-cleaning-and-maintenance-occupations",
      year: "2019",
      number_workers: "1563",
      median_weekly_earnings: "582",
      men_number_workers: "1068",
      men_median_weekly_earnings: "610",
      women_number_workers: "494",
      women_median_weekly_earnings: "510",
      cents_to_dollar: "84"
    },
    {
      slug: "maids-and-housekeeping-cleaners",
      occupation_name: "Maids and housekeeping cleaners",
      parent_slug: "building-and-grounds-cleaning-and-maintenance-occupations",
      year: "2019",
      number_workers: "895",
      median_weekly_earnings: "490",
      men_number_workers: "126",
      men_median_weekly_earnings: "520",
      women_number_workers: "769",
      women_median_weekly_earnings: "484",
      cents_to_dollar: "93"
    },
    {
      slug: "personal-care-and-service-occupations",
      occupation_name: "Personal care and service occupations",
      parent_slug: "service-occupations",
      year: "2019",
      number_workers: "2764",
      median_weekly_earnings: "565",
      men_number_workers: "718",
      men_median_weekly_earnings: "624",
      women_number_workers: "2047",
      women_median_weekly_earnings: "531",
      cents_to_dollar: "85"
    },
    {
      slug: "first-line-supervisors-of-gaming-workers",
      occupation_name: "First-line supervisors of gaming workers",
      parent_slug: "personal-care-and-service-occupations",
      year: "2019",
      number_workers: "117",
      median_weekly_earnings: "821",
      men_number_workers: "63",
      men_median_weekly_earnings: "853",
      women_number_workers: "54",
      women_median_weekly_earnings: "791",
      cents_to_dollar: "93"
    },
    {
      slug: "personal-care-aides",
      occupation_name: "Personal care aides",
      parent_slug: "personal-care-and-service-occupations",
      year: "2019",
      number_workers: "815",
      median_weekly_earnings: "516",
      men_number_workers: "130",
      men_median_weekly_earnings: "581",
      women_number_workers: "685",
      women_median_weekly_earnings: "509",
      cents_to_dollar: "88"
    },
    {
      slug: "recreation-and-fitness-workers",
      occupation_name: "Recreation and fitness workers",
      parent_slug: "personal-care-and-service-occupations",
      year: "2019",
      number_workers: "191",
      median_weekly_earnings: "607",
      men_number_workers: "88",
      men_median_weekly_earnings: "656",
      women_number_workers: "102",
      women_median_weekly_earnings: "580",
      cents_to_dollar: "88"
    },
    {
      slug: "sales-and-office-occupations",
      occupation_name: "Sales and office occupations",
      parent_slug: null,
      year: "2019",
      number_workers: "23883",
      median_weekly_earnings: "758",
      men_number_workers: "9695",
      men_median_weekly_earnings: "874",
      women_number_workers: "14188",
      women_median_weekly_earnings: "713",
      cents_to_dollar: "82"
    },
    {
      slug: "sales-and-related-occupations",
      occupation_name: "Sales and related occupations",
      parent_slug: "sales-and-office-occupations",
      year: "2019",
      number_workers: "9929",
      median_weekly_earnings: "830",
      men_number_workers: "5525",
      men_median_weekly_earnings: "982",
      women_number_workers: "4404",
      women_median_weekly_earnings: "677",
      cents_to_dollar: "69"
    },
    {
      slug: "first-line-supervisors-of-retail-sales-workers",
      occupation_name: "First-line supervisors of retail sales workers",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "2316",
      median_weekly_earnings: "817",
      men_number_workers: "1246",
      men_median_weekly_earnings: "955",
      women_number_workers: "1070",
      women_median_weekly_earnings: "708",
      cents_to_dollar: "74"
    },
    {
      slug: "cashiers",
      occupation_name: "Cashiers",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "1398",
      median_weekly_earnings: "503",
      men_number_workers: "438",
      men_median_weekly_earnings: "510",
      women_number_workers: "959",
      women_median_weekly_earnings: "499",
      cents_to_dollar: "98"
    },
    {
      slug: "retail-salespersons",
      occupation_name: "Retail salespersons",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "1856",
      median_weekly_earnings: "692",
      men_number_workers: "1094",
      men_median_weekly_earnings: "806",
      women_number_workers: "762",
      women_median_weekly_earnings: "578",
      cents_to_dollar: "72"
    },
    {
      slug: "advertising-sales-agents",
      occupation_name: "Advertising sales agents",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "169",
      median_weekly_earnings: "1050",
      men_number_workers: "88",
      men_median_weekly_earnings: "1143",
      women_number_workers: "81",
      women_median_weekly_earnings: "874",
      cents_to_dollar: "76"
    },
    {
      slug: "insurance-sales-agents",
      occupation_name: "Insurance sales agents",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "461",
      median_weekly_earnings: "927",
      men_number_workers: "214",
      men_median_weekly_earnings: "1034",
      women_number_workers: "247",
      women_median_weekly_earnings: "806",
      cents_to_dollar: "78"
    },
    {
      slug: "securities-commodities-and-financial-services-sales-agents",
      occupation_name:
        "Securities, commodities, and financial services sales agents",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "192",
      median_weekly_earnings: "1302",
      men_number_workers: "129",
      men_median_weekly_earnings: "1386",
      women_number_workers: "63",
      women_median_weekly_earnings: "1063",
      cents_to_dollar: "77"
    },
    {
      slug: "sales-representatives-services-all-other",
      occupation_name: "Sales representatives, services, all other",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "477",
      median_weekly_earnings: "1211",
      men_number_workers: "340",
      men_median_weekly_earnings: "1332",
      women_number_workers: "137",
      women_median_weekly_earnings: "973",
      cents_to_dollar: "73"
    },
    {
      slug: "sales-representatives-wholesale-and-manufacturing",
      occupation_name: "Sales representatives, wholesale and manufacturing",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "1107",
      median_weekly_earnings: "1206",
      men_number_workers: "813",
      men_median_weekly_earnings: "1262",
      women_number_workers: "294",
      women_median_weekly_earnings: "1067",
      cents_to_dollar: "85"
    },
    {
      slug: "real-estate-brokers-and-sales-agents",
      occupation_name: "Real estate brokers and sales agents",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "543",
      median_weekly_earnings: "1019",
      men_number_workers: "222",
      men_median_weekly_earnings: "1344",
      women_number_workers: "321",
      women_median_weekly_earnings: "883",
      cents_to_dollar: "66"
    },
    {
      slug: "sales-and-related-workers-all-other",
      occupation_name: "Sales and related workers, all other",
      parent_slug: "sales-and-related-occupations",
      year: "2019",
      number_workers: "194",
      median_weekly_earnings: "935",
      men_number_workers: "123",
      men_median_weekly_earnings: "966",
      women_number_workers: "71",
      women_median_weekly_earnings: "848",
      cents_to_dollar: "88"
    },
    {
      slug: "office-and-administrative-support-occupations",
      occupation_name: "Office and administrative support occupations",
      parent_slug: "sales-and-office-occupations",
      year: "2019",
      number_workers: "13954",
      median_weekly_earnings: "732",
      men_number_workers: "4170",
      men_median_weekly_earnings: "771",
      women_number_workers: "9784",
      women_median_weekly_earnings: "721",
      cents_to_dollar: "94"
    },
    {
      slug:
        "first-line-supervisors-of-office-and-administrative-support-workers",
      occupation_name:
        "First-line supervisors of office and administrative support workers",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "1215",
      median_weekly_earnings: "866",
      men_number_workers: "406",
      men_median_weekly_earnings: "971",
      women_number_workers: "809",
      women_median_weekly_earnings: "816",
      cents_to_dollar: "84"
    },
    {
      slug: "bookkeeping-accounting-and-auditing-clerks",
      occupation_name: "Bookkeeping, accounting, and auditing clerks",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "657",
      median_weekly_earnings: "764",
      men_number_workers: "84",
      men_median_weekly_earnings: "784",
      women_number_workers: "573",
      women_median_weekly_earnings: "764",
      cents_to_dollar: "97"
    },
    {
      slug: "customer-service-representatives",
      occupation_name: "Customer service representatives",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "1977",
      median_weekly_earnings: "693",
      men_number_workers: "717",
      men_median_weekly_earnings: "736",
      women_number_workers: "1259",
      women_median_weekly_earnings: "673",
      cents_to_dollar: "91"
    },
    {
      slug: "receptionists-and-information-clerks",
      occupation_name: "Receptionists and information clerks",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "909",
      median_weekly_earnings: "642",
      men_number_workers: "100",
      men_median_weekly_earnings: "735",
      women_number_workers: "809",
      women_median_weekly_earnings: "636",
      cents_to_dollar: "87"
    },
    {
      slug: "dispatchers",
      occupation_name: "Dispatchers",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "240",
      median_weekly_earnings: "806",
      men_number_workers: "108",
      men_median_weekly_earnings: "854",
      women_number_workers: "131",
      women_median_weekly_earnings: "763",
      cents_to_dollar: "89"
    },
    {
      slug: "postal-service-mail-carriers",
      occupation_name: "Postal service mail carriers",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "296",
      median_weekly_earnings: "951",
      men_number_workers: "185",
      men_median_weekly_earnings: "994",
      women_number_workers: "111",
      women_median_weekly_earnings: "893",
      cents_to_dollar: "90"
    },
    {
      slug: "production-planning-and-expediting-clerks",
      occupation_name: "Production, planning, and expediting clerks",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "268",
      median_weekly_earnings: "939",
      men_number_workers: "114",
      men_median_weekly_earnings: "1039",
      women_number_workers: "154",
      women_median_weekly_earnings: "872",
      cents_to_dollar: "84"
    },
    {
      slug: "shipping-receiving-and-traffic-clerks",
      occupation_name: "Shipping, receiving, and traffic clerks",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "507",
      median_weekly_earnings: "679",
      men_number_workers: "332",
      men_median_weekly_earnings: "686",
      women_number_workers: "175",
      women_median_weekly_earnings: "662",
      cents_to_dollar: "97"
    },
    {
      slug: "secretaries-and-administrative-assistants",
      occupation_name: "Secretaries and administrative assistants",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "2069",
      median_weekly_earnings: "765",
      men_number_workers: "137",
      men_median_weekly_earnings: "795",
      women_number_workers: "1932",
      women_median_weekly_earnings: "763",
      cents_to_dollar: "96"
    },
    {
      slug: "data-entry-keyers",
      occupation_name: "Data entry keyers",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "203",
      median_weekly_earnings: "675",
      men_number_workers: "50",
      men_median_weekly_earnings: "738",
      women_number_workers: "153",
      women_median_weekly_earnings: "656",
      cents_to_dollar: "89"
    },
    {
      slug: "office-clerks-general",
      occupation_name: "Office clerks, general",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "997",
      median_weekly_earnings: "685",
      men_number_workers: "188",
      men_median_weekly_earnings: "718",
      women_number_workers: "809",
      women_median_weekly_earnings: "677",
      cents_to_dollar: "94"
    },
    {
      slug: "office-and-administrative-support-workers-all-other",
      occupation_name: "Office and administrative support workers, all other",
      parent_slug: "office-and-administrative-support-occupations",
      year: "2019",
      number_workers: "522",
      median_weekly_earnings: "866",
      men_number_workers: "147",
      men_median_weekly_earnings: "950",
      women_number_workers: "375",
      women_median_weekly_earnings: "820",
      cents_to_dollar: "86"
    },
    {
      slug: "natural-resources-construction-and-maintenance-occupations",
      occupation_name:
        "Natural resources, construction, and maintenance occupations",
      parent_slug: null,
      year: "2019",
      number_workers: "11671",
      median_weekly_earnings: "869",
      men_number_workers: "11134",
      men_median_weekly_earnings: "881",
      women_number_workers: "537",
      women_median_weekly_earnings: "614",
      cents_to_dollar: "70"
    },
    {
      slug: "farming-fishing-and-forestry-occupations",
      occupation_name: "Farming, fishing, and forestry occupations",
      parent_slug: "natural-resources-construction-and-maintenance-occupations",
      year: "2019",
      number_workers: "900",
      median_weekly_earnings: "574",
      men_number_workers: "690",
      men_median_weekly_earnings: "593",
      women_number_workers: "210",
      women_median_weekly_earnings: "513",
      cents_to_dollar: "87"
    },
    {
      slug: "miscellaneous-agricultural-workers",
      occupation_name: "Miscellaneous agricultural workers",
      parent_slug: "farming-fishing-and-forestry-occupations",
      year: "2019",
      number_workers: "691",
      median_weekly_earnings: "558",
      men_number_workers: "544",
      men_median_weekly_earnings: "581",
      women_number_workers: "148",
      women_median_weekly_earnings: "502",
      cents_to_dollar: "86"
    },
    {
      slug: "construction-and-extraction-occupations",
      occupation_name: "Construction and extraction occupations",
      parent_slug: "natural-resources-construction-and-maintenance-occupations",
      year: "2019",
      number_workers: "6467",
      median_weekly_earnings: "866",
      men_number_workers: "6280",
      men_median_weekly_earnings: "873",
      women_number_workers: "187",
      women_median_weekly_earnings: "711",
      cents_to_dollar: "81"
    },
    {
      slug: "installation-maintenance-and-repair-occupations",
      occupation_name: "Installation, maintenance, and repair occupations",
      parent_slug: "production-transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "4304",
      median_weekly_earnings: "939",
      men_number_workers: "4164",
      men_median_weekly_earnings: "943",
      women_number_workers: "140",
      women_median_weekly_earnings: "850",
      cents_to_dollar: "90"
    },
    {
      slug: "production-transportation-and-material-moving-occupations",
      occupation_name:
        "Production, transportation, and material moving occupations",
      parent_slug: null,
      year: "2019",
      number_workers: "15353",
      median_weekly_earnings: "727",
      men_number_workers: "12020",
      men_median_weekly_earnings: "780",
      women_number_workers: "3334",
      women_median_weekly_earnings: "593",
      cents_to_dollar: "76"
    },
    {
      slug: "production-occupations",
      occupation_name: "Production occupations",
      parent_slug: "production-transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "7741",
      median_weekly_earnings: "745",
      men_number_workers: "5668",
      men_median_weekly_earnings: "814",
      women_number_workers: "2073",
      women_median_weekly_earnings: "596",
      cents_to_dollar: "73"
    },
    {
      slug: "first-line-supervisors-of-production-and-operating-workers",
      occupation_name:
        "First-line supervisors of production and operating workers",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "806",
      median_weekly_earnings: "949",
      men_number_workers: "633",
      men_median_weekly_earnings: "1031",
      women_number_workers: "173",
      women_median_weekly_earnings: "721",
      cents_to_dollar: "70"
    },
    {
      slug: "electrical-electronics-and-electromechanical-assemblers",
      occupation_name:
        "Electrical, electronics, and electromechanical assemblers",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "103",
      median_weekly_earnings: "644",
      men_number_workers: "52",
      men_median_weekly_earnings: "712",
      women_number_workers: "51",
      women_median_weekly_earnings: "594",
      cents_to_dollar: "83"
    },
    {
      slug: "miscellaneous-assemblers-and-fabricators",
      occupation_name: "Miscellaneous assemblers and fabricators",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "900",
      median_weekly_earnings: "684",
      men_number_workers: "574",
      men_median_weekly_earnings: "724",
      women_number_workers: "326",
      women_median_weekly_earnings: "597",
      cents_to_dollar: "82"
    },
    {
      slug: "bakers",
      occupation_name: "Bakers",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "151",
      median_weekly_earnings: "561",
      men_number_workers: "70",
      men_median_weekly_earnings: "590",
      women_number_workers: "81",
      women_median_weekly_earnings: "522",
      cents_to_dollar: "88"
    },
    {
      slug: "butchers-and-other-meat-poultry-and-fish-processing-workers",
      occupation_name:
        "Butchers and other meat, poultry, and fish processing workers",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "265",
      median_weekly_earnings: "648",
      men_number_workers: "198",
      men_median_weekly_earnings: "671",
      women_number_workers: "67",
      women_median_weekly_earnings: "573",
      cents_to_dollar: "85"
    },
    {
      slug: "food-processing-workers-all-other",
      occupation_name: "Food processing workers, all other",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "144",
      median_weekly_earnings: "658",
      men_number_workers: "94",
      men_median_weekly_earnings: "779",
      women_number_workers: "50",
      women_median_weekly_earnings: "573",
      cents_to_dollar: "74"
    },
    {
      slug: "metal-workers-and-plastic-workers-all-other",
      occupation_name: "Metal workers and plastic workers, all other",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "385",
      median_weekly_earnings: "736",
      men_number_workers: "312",
      men_median_weekly_earnings: "795",
      women_number_workers: "74",
      women_median_weekly_earnings: "592",
      cents_to_dollar: "74"
    },
    {
      slug: "inspectors-testers-sorters-samplers-and-weighers",
      occupation_name: "Inspectors, testers, sorters, samplers, and weighers",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "722",
      median_weekly_earnings: "835",
      men_number_workers: "463",
      men_median_weekly_earnings: "939",
      women_number_workers: "259",
      women_median_weekly_earnings: "693",
      cents_to_dollar: "74"
    },
    {
      slug: "packaging-and-filling-machine-operators-and-tenders",
      occupation_name: "Packaging and filling machine operators and tenders",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "244",
      median_weekly_earnings: "575",
      men_number_workers: "116",
      men_median_weekly_earnings: "646",
      women_number_workers: "128",
      women_median_weekly_earnings: "533",
      cents_to_dollar: "83"
    },
    {
      slug: "production-workers-all-other",
      occupation_name: "Production workers, all other",
      parent_slug: "production-occupations",
      year: "2019",
      number_workers: "1056",
      median_weekly_earnings: "704",
      men_number_workers: "763",
      men_median_weekly_earnings: "767",
      women_number_workers: "293",
      women_median_weekly_earnings: "566",
      cents_to_dollar: "74"
    },
    {
      slug: "transportation-and-material-moving-occupations",
      occupation_name: "Transportation and material moving occupations",
      parent_slug: "production-transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "7612",
      median_weekly_earnings: "711",
      men_number_workers: "6352",
      men_median_weekly_earnings: "747",
      women_number_workers: "1260",
      women_median_weekly_earnings: "586",
      cents_to_dollar: "78"
    },
    {
      slug: "bus-drivers",
      occupation_name: "Bus drivers",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "364",
      median_weekly_earnings: "674",
      men_number_workers: "205",
      men_median_weekly_earnings: "718",
      women_number_workers: "159",
      women_median_weekly_earnings: "625",
      cents_to_dollar: "87"
    },
    {
      slug: "driver-sales-workers-and-truck-drivers",
      occupation_name: "Driver/sales workers and truck drivers",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "2723",
      median_weekly_earnings: "843",
      men_number_workers: "2564",
      men_median_weekly_earnings: "861",
      women_number_workers: "159",
      women_median_weekly_earnings: "660",
      cents_to_dollar: "77"
    },
    {
      slug: "taxi-drivers-and-chauffeurs",
      occupation_name: "Taxi drivers and chauffeurs",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "406",
      median_weekly_earnings: "614",
      men_number_workers: "356",
      men_median_weekly_earnings: "624",
      women_number_workers: "50",
      women_median_weekly_earnings: "520",
      cents_to_dollar: "83"
    },
    {
      slug: "industrial-truck-and-tractor-operators",
      occupation_name: "Industrial truck and tractor operators",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "541",
      median_weekly_earnings: "677",
      men_number_workers: "489",
      men_median_weekly_earnings: "686",
      women_number_workers: "52",
      women_median_weekly_earnings: "625",
      cents_to_dollar: "91"
    },
    {
      slug: "laborers-and-freight-stock-and-material-movers-hand",
      occupation_name: "Laborers and freight, stock, and material movers, hand",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "1764",
      median_weekly_earnings: "634",
      men_number_workers: "1402",
      men_median_weekly_earnings: "657",
      women_number_workers: "362",
      women_median_weekly_earnings: "567",
      cents_to_dollar: "86"
    },
    {
      slug: "packers-and-packagers-hand",
      occupation_name: "Packers and packagers, hand",
      parent_slug: "transportation-and-material-moving-occupations",
      year: "2019",
      number_workers: "467",
      median_weekly_earnings: "530",
      men_number_workers: "202",
      men_median_weekly_earnings: "576",
      women_number_workers: "265",
      women_median_weekly_earnings: "515",
      cents_to_dollar: "89"
    }
  ],
  all: function() {
    return this.gaps;
  },
  get: function(slug) {
    const isGap = g => g.slug === slug;
    return this.gaps.find(isGap);
  },
  random: function(excludeSlug) {
    const gapsExcludingSlug = this.gaps.filter(
      gap =>
        gap.slug !== excludeSlug &&
        gap.slug !== "total-full-time-wage-and-salary-workers"
    );

    return gapsExcludingSlug[
      Math.floor(Math.random() * gapsExcludingSlug.length)
    ];
  },
  cleanOccupationName: function(occupationName) {
    let cleanName = occupationName.toLowerCase();
    //ends with , hand
    if (cleanName.endsWith(", hand")) {
      return this.cutOffSuffix(cleanName, ", hand");
    }
    //ends with , all other
    if (cleanName.endsWith(", all other")) {
      return this.cutOffSuffix(cleanName, ", all other");
    }
    //starts with miscellaneous
    if (cleanName.startsWith("miscellaneous ")) {
      return cleanName.substring("miscellaneous ".length);
    }
    //starts with other
    if (cleanName.startsWith("other ")) {
      return cleanName.substring("other ".length);
    }
    //waitresses and waiters - waiters
    if (cleanName === "waiters and waitresses") {
      return "waitresses";
    }
    //total, 16 years and over just 16 years and over
    if (cleanName === "total, full-time wage and salary workers") {
      return "in the U.S.";
    }
    return cleanName;
  },
  cutOffSuffix: (str, suffix) => str.substring(0, str.length - suffix.length),
  capitalize: str => str.charAt(0).toUpperCase() + str.slice(1)
};

export default GapAPI;
